
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::888121514691:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-lvNXuR3PHnck
      username: system:node:{{EC2PrivateDNSName}}
        mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::888121514691:user/sameks
      username: sameks
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-20T09:47:27Z"
  name: aws-auth
  namespace: kube-system
  uid: 4b9d553d-342d-40da-af45-ba705ed6ea5a
